In [1]:
import numpy as np

In [7]:
board = np.zeros((3,3,3)).astype(int)
board

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [8]:
board[0,0,0] = 1
board[0,1,1] = 1
board[0,2,2] = 1
board

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [9]:
board[1,0,0] = 2
board[1,1,1] = 2
board[1,1,2] = 2
board

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [10]:
board[2,0,0] = 3
board

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [11]:
players = 4
scores = {}

scores = {n+1:0 for n in range(players)}

scores

{1: 0, 2: 0, 3: 0, 4: 0}

In [12]:
[0,0,0], [0,0,1], [0,0,2]
[0,1,0], [0,1,1], [0,1,2]
[0,2,0], [0,2,1], [0,2,2]

[1,0,0], [1,0,1], [1,0,2]
[1,1,0], [1,1,1], [1,1,2]
[1,2,0], [1,2,1], [1,2,2]

[2,0,0], [2,0,1], [2,0,2]
[2,1,0], [2,1,1], [2,1,2]
[2,2,0], [2,2,1], [2,2,2]

([2, 2, 0], [2, 2, 1], [2, 2, 2])

In [13]:
position = [0,0,0]
position = tuple(position)

In [14]:
board[position] = 5
board

array([[[5, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [15]:
board[0,2,1]

0

In [16]:
legal_actions = np.argwhere(board == 0).tolist()
legal_actions

[[0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 1],
 [2, 0, 2],
 [2, 1, 0],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1],
 [2, 2, 2]]

In [17]:
action = legal_actions.pop()
action

[2, 2, 2]

In [18]:
position = tuple(action)
position

(2, 2, 2)

In [19]:
action[0]

2

In [20]:
board[position] = 5
board

array([[[5, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 5]]])

In [21]:
mark = 'A'
pieces = {}
pieces[0] = [mark+'1',mark+'1',mark+'1']
pieces[1] = [mark+'2',mark+'2',mark+'2']
pieces[2] = [mark+'3',mark+'3',mark+'3']

pieces

{0: ['A1', 'A1', 'A1'], 1: ['A2', 'A2', 'A2'], 2: ['A3', 'A3', 'A3']}

In [22]:
board

array([[[5, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 5]]])

In [23]:
pieces = {}
pieces[0] = [mark+'1',mark+'1',mark+'1']
pieces[1] = [mark+'2',mark+'2',mark+'2']
pieces[2] = [mark+'3',mark+'3',mark+'3']

pieces

{0: ['A1', 'A1', 'A1'], 1: ['A2', 'A2', 'A2'], 2: ['A3', 'A3', 'A3']}

In [24]:
invalid_player_levels = [k for k,v in pieces.items() if len(v)==0]
invalid_player_levels

[]

In [25]:
player_legal_board = board
player_legal_board

array([[[5, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 2, 2],
        [0, 0, 0]],

       [[3, 0, 0],
        [0, 0, 0],
        [0, 0, 5]]])

In [26]:
legal_actions = np.argwhere(player_legal_board == 0).tolist()
legal_actions

[[0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 1],
 [2, 0, 2],
 [2, 1, 0],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1]]

In [27]:
[x for x in legal_actions if x[0] not in invalid_player_levels]

[[0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 1],
 [2, 0, 2],
 [2, 1, 0],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1]]

In [28]:
pieces[action[0]].pop()

'A3'

In [29]:
win_conditions = {

            "Level 1 top_row":[[0,0,0], [0,0,1], [0,0,2]],
            "Level 1 mid_row":[[0,1,0], [0,1,1], [0,1,2]],
            "Level 1 bot_row":[[0,2,0], [0,2,1], [0,2,2]],
            "Level 1 left_col":[[0,0,0],[0,1,0], [0,2,0]],
            "Level 1 mid_col":[[0,0,1], [0,1,1], [0,1,2]],
            "Level 1 right_col":[[0,0,2], [0,1,2], [0,2,2]],
            "Level 1 left_diag":[[0,0,0], [0,1,1], [0,2,2]],
            "Level 1 right_diag":[[0,0,2], [0,1,1], [0,2,0]],

            "Level 2 top_row":[[1,0,0], [1,0,1], [1,0,2]],
            "Level 2 mid_row":[[1,1,0], [1,1,1], [1,1,2]],
            "Level 2 bot_row":[[1,2,0], [1,2,1], [1,2,2]],
            "Level 2 left_col":[[1,0,0], [1,1,0], [1,2,0]],
            "Level 2 mid_col":[[1,0,1], [1,1,1], [1,2,1]],
            "Level 2 right_col":[[1,0,2], [1,1,2], [1,2,2]],
            "Level 2 left_diag":[[1,0,0], [1,1,1], [1,2,2]],
            "Level 2 right_diag":[[1,0,2], [1,1,1], [1,2,0]],
            
            "Level 3 top_row":[[2,0,0], [2,0,1], [2,0,2]],
            "Level 3 mid_row":[[2,1,0], [2,1,1], [2,1,2]],
            "Level 3 bot_row":[[2,2,0], [2,2,1], [2,2,2]],
            "Level 3 left_col":[[2,0,0], [2,1,0], [2,2,0]],
            "Level 3 mid_col":[[2,0,1], [2,1,1], [2,2,1]],
            "Level 3 right_col":[[2,0,2], [2,1,2], [2,2,2]],
            "Level 3 left_diag":[[2,0,0], [2,1,1], [2,2,2]],
            "Level 3 right_diag":[[2,0,2], [2,1,1], [2,2,0]],

            "Single Column 0,0":[[0,0,0], [1,0,0], [2,0,0]],
            "Single Column 0,1":[[0,0,1], [1,0,1], [2,0,1]],
            "Single Column 0,2":[[0,0,2], [1,0,2], [2,0,2]],
            "Single Column 1,0":[[0,1,0], [1,1,0], [2,1,0]],
            "Single Column 1,1":[[0,1,1], [1,1,1], [2,1,1]],
            "Single Column 1,2":[[0,1,2], [1,1,2], [2,1,2]],
            "Single Column 2,0":[[0,2,0], [1,2,0], [2,2,0]],
            "Single Column 2,1":[[0,2,1], [1,2,1], [2,2,1]],
            "Single Column 2,2":[[0,2,2], [1,2,2], [2,2,2]],

            "Diag top_row asc":[[0,0,0], [1,0,1], [2,0,2]],
            "Diag top_row desc":[[2,0,0], [1,0,1], [0,0,2]],
            "Diag mid_row asc":[[0,1,0], [1,1,1], [2,1,2]],
            "Diag mid_row desc":[[2,1,0], [1,1,1], [0,0,2]],
            "Diag bot_row asc":[[0,2,0], [1,2,1], [2,2,2]],
            "Diag bot_row desc":[[2,2,0], [1,2,1], [0,2,2]],
            "Diag left_col asc":[[0,0,0], [1,1,0], [2,2,0]],
            "Diag left_col desc":[[0,2,0], [1,1,0], [2,0,0]],
            "Diag mid_col asc":[[0,0,1], [1,1,1], [2,2,1]],
            "Diag mid_col desc":[[0,2,1], [1,1,1], [2,0,1]],
            "Diag right_col asc":[[0,0,2], [1,1,2], [2,2,2]],
            "Diag right_col desc":[[2,2,2], [1,1,2], [0,0,2]],
            "Diag left_diag asc":[[0,0,0], [1,1,1], [2,2,2]],
            "Diag right_diag asc":[[2,0,0], [1,1,1], [0,2,2]],
            "Diag left_diag desc":[[0,2,0], [1,1,1], [2,0,2]],
            "Diag right_diag desc":[[2,2,0], [1,1,1], [0,0,2]],

                }

## Win Conditions

In [33]:
win_array = list(win_conditions.values())
win_array

[[[0, 0, 0], [0, 0, 1], [0, 0, 2]],
 [[0, 1, 0], [0, 1, 1], [0, 1, 2]],
 [[0, 2, 0], [0, 2, 1], [0, 2, 2]],
 [[0, 0, 0], [0, 1, 0], [0, 2, 0]],
 [[0, 0, 1], [0, 1, 1], [0, 1, 2]],
 [[0, 0, 2], [0, 1, 2], [0, 2, 2]],
 [[0, 0, 0], [0, 1, 1], [0, 2, 2]],
 [[0, 0, 2], [0, 1, 1], [0, 2, 0]],
 [[1, 0, 0], [1, 0, 1], [1, 0, 2]],
 [[1, 1, 0], [1, 1, 1], [1, 1, 2]],
 [[1, 2, 0], [1, 2, 1], [1, 2, 2]],
 [[1, 0, 0], [1, 1, 0], [1, 2, 0]],
 [[1, 0, 1], [1, 1, 1], [1, 2, 1]],
 [[1, 0, 2], [1, 1, 2], [1, 2, 2]],
 [[1, 0, 0], [1, 1, 1], [1, 2, 2]],
 [[1, 0, 2], [1, 1, 1], [1, 2, 0]],
 [[2, 0, 0], [2, 0, 1], [2, 0, 2]],
 [[2, 1, 0], [2, 1, 1], [2, 1, 2]],
 [[2, 2, 0], [2, 2, 1], [2, 2, 2]],
 [[2, 0, 0], [2, 1, 0], [2, 2, 0]],
 [[2, 0, 1], [2, 1, 1], [2, 2, 1]],
 [[2, 0, 2], [2, 1, 2], [2, 2, 2]],
 [[2, 0, 0], [2, 1, 1], [2, 2, 2]],
 [[2, 0, 2], [2, 1, 1], [2, 2, 0]],
 [[0, 0, 0], [1, 0, 0], [2, 0, 0]],
 [[0, 0, 1], [1, 0, 1], [2, 0, 1]],
 [[0, 0, 2], [1, 0, 2], [2, 0, 2]],
 [[0, 1, 0], [1, 1, 0], [2, 

In [34]:
len(win_array)

49

In [35]:
remove_conditions = []

In [32]:
board[0,0,0] = 3
board[0,0,1] = 5
board[0,0,2] = 7
board[1,1,1] = 9
board[2,2,2] = 11
board[2,2,1] = 11
board[2,2,0] = 11
board[1,0,1] = 5
board[1,2,1] = 8
board[1,0,2] = 2
board[1,2,2] = 2
board[0,1,0] = 1
board[0,1,2] = 1
board

array([[[ 3,  5,  7],
        [ 1,  1,  1],
        [ 0,  0,  1]],

       [[ 2,  5,  2],
        [ 0,  9,  2],
        [ 0,  8,  2]],

       [[ 3,  0,  0],
        [ 0,  0,  0],
        [11, 11, 11]]])

In [49]:
for single_win_condition in win_array:
    test_indices = [tuple(x) for x in single_win_condition] 
    test_win_contents = [board[i] for i in test_indices]
    print('\n'+str(test_win_contents))
    if 0 not in test_win_contents and not all(element == test_win_contents[0] for element in test_win_contents):
        print("Win condition is removed, but game is not over")
        remove_conditions.append(single_win_condition)
    elif 0 not in test_win_contents and all(element == test_win_contents[0] for element in test_win_contents):
        print("Game is over:")
        print(single_win_condition)
    else:
        pass
for i in remove_conditions:
    win_array.remove(i)


[1, 1, 1]
Game is over:
[[0, 1, 0], [0, 1, 1], [0, 1, 2]]

[0, 0, 1]

[3, 1, 0]

[7, 1, 0]

[0, 9, 2]

[0, 8, 2]

[2, 0, 0]

[2, 2, 2]
Game is over:
[[1, 0, 2], [1, 1, 2], [1, 2, 2]]

[2, 9, 0]

[3, 0, 0]

[0, 0, 0]

[11, 11, 11]
Game is over:
[[2, 2, 0], [2, 2, 1], [2, 2, 2]]

[3, 0, 11]

[0, 0, 11]

[0, 0, 11]

[3, 0, 11]

[0, 0, 11]

[5, 5, 0]

[7, 2, 0]

[1, 0, 0]

[1, 9, 0]

[1, 2, 0]

[0, 0, 11]

[0, 8, 11]

[3, 5, 0]

[1, 9, 0]

[0, 9, 7]

[0, 8, 11]

[3, 0, 11]

[0, 0, 3]

[0, 9, 0]

[0, 9, 0]


ValueError: list.remove(x): x not in list

In [270]:
test_win_contents[0]

11

In [258]:
remove_conditions

[[[0, 0, 0], [0, 0, 1], [0, 0, 2]], [[1, 0, 1], [1, 1, 1], [1, 2, 1]]]

In [259]:
for i in remove_conditions:
    win_array.remove(i)

In [260]:
len(win_array)

47

In [273]:
player_winner = 2
scores

{1: 0, 2: 0, 3: 0, 4: 0}

In [305]:
for k in scores.keys():
    if k != player_winner:
        scores[k] = -10

1
3
4


In [228]:
first_win_condition = win_array[0]
first_win_condition

[[0, 0, 0], [0, 0, 1], [0, 0, 2]]

In [229]:
test_indices = [tuple(x) for x in first_win_condition]
test_indices

[(0, 0, 0), (0, 0, 1), (0, 0, 2)]

In [230]:
test_win_contents = [board[i] for i in test_indices]
test_win_contents

[3, 5, 7]

In [235]:
if 0 not in test_win_contents and all(element == test_win_contents[0] for element in test_win_contents):
    print("Game is over")
else:
    print("Game is not over")
    


True


In [ ]:
checked_win_conditions = []

In [232]:
test_win_contents.items()

AttributeError: 'list' object has no attribute 'items'